language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "KwVm1yOhsdWrIylTL1MVKrN41YyfzguQiJryuYQIwOn5JrcIETYR2Lzd97qUz1IiI4rtSh7cIH66lMoyghTFV7ruCaxAt4r/grI8q+/29VqBhD9oysEhKaIgWRUp5e2/bhWQ20HTx2/Me+KVIoXWFiwz2LQuOyWLFcxIIn8tF6iaqVHEF67uXlP7OjNWgl+AUZ94veshPYCF+J2HNSQhG8uqZNE4K9V0aem/B6r/Dh7XCr/s3kz1sf4v1u9eWo6j27+iIGzwPkfnSxU9aC5wprtVeHjQaft4zLRRsfe0+zOhAyjXmZ25XO4ehN6U3gQKk2/LUmDll+4a2iTaySQ5MDYQjcwtDfPxyGfx6GdpZ+plt+3JI84VV/IQcI7YlXp8v0ZQDbfxsooDH8t2xgoc20vXJylSsVn8Jaj2E8IppoSjmVrGR/b0v0SXP88e14Xet1dsf0IFt1oMh1qj3IzxLeVBoPiii2SBcnpF9pdNIjt6D/TaA0gDnCPZI6kjBZb0CCgg0ur8meoX80VS5dovfilp7KmPnjuKqEHtf8kBsU0oOe69yI2EisGXin2NIZGZk0nHzwY6ZTsXz8cNHfD9N/PojKn4htku1ijWQNRNE2+YaiqGx63tr1Y21XDYevUF64p12u5ef1k9atCw1xfPhclyR3IkrG0Eu2rtxsUeqNM="
  secret_access_key:
    secure: "ytdkQvmFPmnLH4pqKk+j9WuvOwm4j51G+Aq69dnvn2jo1JXbqlzTb5cSfQKsyGImMlAo0H2ua1O+NBlvdMP7V/7FWcCWr7Fid/FRwOBpr5HbYkmgRvbo/s0rlkgfAKg1Ujp8X+iqFtzpjddwRjM7RMM1PeFfnfvzZt6V3RedtoAIsFVQ7zTy7eusD7Zu0ak3K4c0VXOsi9vX3YaHA/QdwSLAun56+XABc/t5RLzWU2NNrpjwn9EEUyoytq0CI93ME0kQ48q2SXMKVNjWUDvlfAx4MXjV4KSrU1RpDmyMXFZEwPP1v/344IU/N/KStNTsz6ydci0NK54um3n4Qaadv1TyqOMhhtEVi9/BDVziz8bxAfXiRxAIOC2rLxf2Ves0R3/pwvXPBcPi0+QTExQZADGhJ4f8kgGoqpnUZ2sQfFT4v22mJwWtXVVBeu1gplGuMoW7QuE3j+hVgHq2w0tj/67d2SlGfxuuA0DjGHOiGV6xUHSe9cXoQZRlVunu9qSwqDkFXxcZwfVSpyi2zCkQb7rlJYtJdH7dYq5dIdfftvK+kVDOE0L4YodCQ9/ekrLd0Y1uBtb60GXyEigwsMZ0Zh+Vil8zKSJwanjCq2Un/CWqH94JQmh1spikD8DW9i3uLuM2QrLSMEe5RgJOviSMcALsQBlYvtHmjABC7f87mFQ="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
  upload_dir: projects/nhl
